#!/bin/bash
pandoc ./markdown/*.md \
--output index.html \
--css style.css \
--template ./templates/main.html \
--include-before-body ./templates/nav.html \
--toc \
--toc-depth=1 \
--title-prefix="MassMine eBook" \
--smart

#pandoc -S -o mmtraining.epub title.txt \
#intro/intro.md \
#chap1/chap1.md \
#chap2/chap2.md \
#--epub-stylesheet epubstyle.css

#pandoc -S -o mmtraining.html \
#intro/intro.md \
#chap1/chap1.md \
#chap2/chap2.md \
#--template template.html \
#--css pandoc.css \
#--toc \
#--toc-depth=1

#pandoc -S -o mmtraining.pdf \
#intro/intro.md \
#chap1/chap1.md \
#chap2/chap2.md \
#--latex-engine=pdflatex

#git add --all
#git commit -m "docs update"
#git push
